import os
from dotenv import load_dotenv
from datetime import time

load_dotenv(override=True)

BYBIT_API_KEY = os.getenv("BYBIT_API_KEY", "")
BYBIT_API_SECRET = os.getenv("BYBIT_API_SECRET", "")
BYBIT_TESTNET = os.getenv("BYBIT_TESTNET", "true").lower() == "true"
BYBIT_DEMO_TRADING = os.getenv("BYBIT_DEMO_TRADING", "false").lower() == "true"
FAST_TEST_MODE = os.getenv("FAST_TEST_MODE", "false").lower() == "true"
FLOW_TEST_MODE = os.getenv("FLOW_TEST_MODE", "false").lower() == "true"
FLOW_TEST_SYMBOL = os.getenv("FLOW_TEST_SYMBOL", "ADAUSDT")
FLOW_TEST_SIDE = os.getenv("FLOW_TEST_SIDE", "LONG").upper()
FLOW_TEST_FORCE_WEAK_MODE = os.getenv("FLOW_TEST_FORCE_WEAK_MODE", "false").lower() == "true"
FLOW_TEST_DISABLE_NO_CHASE = os.getenv("FLOW_TEST_DISABLE_NO_CHASE", "true").lower() == "true"
TRADING_MODE = os.getenv("TRADING_MODE", "sabah").strip().lower()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

TIMEZONE_OFFSET = 3

STRATEGY_CONFIG = {
    "ema_fast": 20,
    "ema_mid": 50,
    "ema_slow": 50,
    "ema_trend": 200,
    "ema_length": 50,
    "ema_slope_lookback": 3,
    "min_ema_slope_percent": 0.05,
    "rsi_length": 14,
    "rsi_oversold": 30,
    "rsi_overbought": 70,
    "macd_fast": 12,
    "macd_slow": 26,
    "macd_signal": 9,
    "atr_length": 14,
    "atr_multiplier": 1.5,
    "adx_length": 14,
    "adx_min_trend": 20,
    "adx_strong_trend": 25,
    "volume_spike_mult": 1.3,
    "volume_confirm_mult": 0.8,
    "swing_lookback": 10,
    "volume_length": 20,
    "volume_multiplier": float(os.getenv("VOLUME_MULTIPLIER", 1.2)),
    "min_body_ratio": 0.35,
    "strong_body_ratio": 0.55,
    "min_rr": float(os.getenv("MIN_RR", 1.70)),
    "min_sl_percent": 0.25,
    "max_sl_percent": 2.5,
    "tp1_rr": float(os.getenv("TP1_RR", 1.7)),
    "tp1_percent": float(os.getenv("TP1_PERCENT", 40)),
    "tp2_rr": float(os.getenv("TP2_RR", 2.1)),
    "tp2_percent": float(os.getenv("TP2_PERCENT", 35)),
    "tp3_rr": float(os.getenv("TP3_RR", 2.6)),
    "tp3_percent": float(os.getenv("TP3_PERCENT", 25)),
    "weak_tp1_rr": float(os.getenv("WEAK_TP1_RR", 1.7)),
    "weak_tp2_rr": float(os.getenv("WEAK_TP2_RR", 2.1)),
    "weak_tp3_rr": float(os.getenv("WEAK_TP3_RR", 2.6)),
    "weak_tp1_percent": float(os.getenv("WEAK_TP1_PERCENT", 50)),
    "weak_tp2_percent": float(os.getenv("WEAK_TP2_PERCENT", 25)),
    "weak_tp3_percent": float(os.getenv("WEAK_TP3_PERCENT", 25)),
    "weak_ema_gap_bps": 25,
    "aggressive_entry_enabled": True,
    "aggressive_distance_atr": 0.6,
    "aggressive_entry_offset_atr": 0.15,
    "impulse_lookback": 8,
    "sl_buffer1_atr": 0.15,
    "sl_buffer2_atr": 0.20,
    "sl_be_offset_atr": 0.0,
    "sl_trail_trigger_offset_atr": 0.10,
    "sl_trail_limit_offset_atr": 0.15,
    "setup_min_candles": 3,
    "setup_max_candles": 12,
    "setup_timeout_min_minutes": 15,
    "setup_timeout_max_minutes": 60,
    "pivot_n": 2,
    "hold_tolerance_bps": 4,
    "two_candle_hh_ll_enabled": False,
    "bias_min_ema_gap_bps": 12,
    "ema_stack_relaxed_mode": True,
    "ema_stack_relaxed_ema200_tolerance_bps": 18,
    "break_min_atr": 0.0,
    "pullback_band_atr": 0.0,
    "range_mode_enabled": False,
    "range_entry_deviation_atr": 0.75,
    "range_rsi_long_max": 38,
    "range_rsi_short_min": 62,
    "range_stop_atr": 0.55,
    "range_stop_buffer_atr": 0.12,
    "weak_mode_enabled": False,
    "setup_lookback_1h": 30,
    "sweep_lookback_15m": 16,
    "btc_chop_atr_mult": 0.12,
    "alt_chop_atr_mult": 0.18,
    "btc_30m_chop_atr_mult": 0.12,
    "alt_30m_chop_atr_mult": 0.18,
    "btc_sweep_spike_atr_mult": 3.0,
    "alt_sweep_spike_atr_mult": 3.8,
    "entry_zone_atr_mult": 0.35,
    "entry_bos_confirm_enabled": False,
    "sl_buffer_atr": 0.18,
    "btc_sl_min_atr": 0.40,
    "btc_sl_max_atr": 1.55,
    "alt_sl_min_atr": 0.45,
    "alt_sl_max_atr": 1.80,
    "quality_min_score": 1,
    "min_total_score": float(os.getenv("MIN_TOTAL_SCORE", 3.5)),
    "strong_total_score": 7.5,
    "rr_hard_min": 1.0,
    "rr_soft_penalty": -1.5,
    "impulse_far_penalty": -1.5,
    "levels_fallback_penalty_30m": -0.8,
    "levels_fallback_penalty_atr": -1.5,
    "impulse_score_min_atr": 1.8,
    "retest_entry_score": 4.0,
    "continuation_entry_score": 2.2,
    "htf_alignment_bonus": float(os.getenv("HTF_ALIGNMENT_BONUS", 0.8)),
    "htf_countertrend_penalty": float(os.getenv("HTF_COUNTERTREND_PENALTY", 1.0)),
    "block_against_full_htf_consensus": os.getenv("BLOCK_AGAINST_FULL_HTF_CONSENSUS", "true").lower() == "true",
    "psychology_enabled": os.getenv("PSYCHOLOGY_ENABLED", "true").lower() == "true",
    "psych_round_number_bonus": float(os.getenv("PSYCH_ROUND_NUMBER_BONUS", 0.5)),
    "psych_round_number_penalty": float(os.getenv("PSYCH_ROUND_NUMBER_PENALTY", 0.7)),
    "psych_round_level_tolerance_bps": float(os.getenv("PSYCH_ROUND_LEVEL_TOLERANCE_BPS", 25)),
    "psych_test_count_bonus": float(os.getenv("PSYCH_TEST_COUNT_BONUS", 0.4)),
    "psych_rsi_crowded_long": float(os.getenv("PSYCH_RSI_CROWDED_LONG", 68)),
    "psych_rsi_crowded_short": float(os.getenv("PSYCH_RSI_CROWDED_SHORT", 32)),
    "soft_trend_requires_15m_alignment": os.getenv("SOFT_TREND_REQUIRES_15M_ALIGNMENT", "true").lower() == "true",
    "psych_rsi_crowded_penalty": float(os.getenv("PSYCH_RSI_CROWDED_PENALTY", 0.6)),
    "use_retest_buffer_sl": True,
    "retest_sl_buffer_atr": 0.22,
    "retest_sl_limit_buffer_atr": 0.12,
    "setup_timeout_minutes": 60,
    "max_hold_time_minutes": 60,
}

EXECUTION_CONFIG = {
    "timeframe": os.getenv("EXECUTION_TIMEFRAME", "5"),
    "entry_timeout_minutes": 60,
    "min_setup_wait_minutes": int(os.getenv("MIN_SETUP_WAIT_MINUTES", 15)),
    "trigger_wait_candles": 4,
    "setup_requeue_cooldown_minutes": int(os.getenv("SETUP_REQUEUE_COOLDOWN_MINUTES", 15)),
    "setup_fingerprint_round_atr": float(os.getenv("SETUP_FINGERPRINT_ROUND_ATR", 0.35)),
    "entry_order_type": "limit",
    "tp_trigger_by_last": True,
    "collect_setups_while_open_position": True,
    "max_pending_setups": 20,
    "max_chase_atr": float(os.getenv("MAX_CHASE_ATR", 0.35)),
    "hard_no_chase_atr": float(os.getenv("HARD_NO_CHASE_ATR", 0.55)),
    "hard_chase_reanchor_enabled": os.getenv("HARD_CHASE_REANCHOR_ENABLED", "true").lower() == "true",
    "hard_chase_reanchor_max_atr": float(os.getenv("HARD_CHASE_REANCHOR_MAX_ATR", 0.90)),
    "hard_chase_reanchor_min_score": float(os.getenv("HARD_CHASE_REANCHOR_MIN_SCORE", 10.0)),
    "ema_anchor_entry": True,
    "ema_anchor_buffer_bps": 2,
    "ema_anchor_max_distance_atr": 1.2,
    "sr_lookback_candles": 24,
    "breakout_retest_tolerance_bps": 8,
    "limit_offset_bps": 1,
    "use_post_only": True,
    "reprice_once": True,
    "reprice_offset_bps": 1,
    "cancel_wait_timeframe": "5",
    "cancel_after_candles": int(os.getenv("CANCEL_AFTER_CANDLES", 2)),
    "pullback_tolerance_bps": int(os.getenv("PULLBACK_TOLERANCE_BPS", 3)),
    "max_retest_deviation_pct": float(os.getenv("MAX_RETEST_DEVIATION_PCT", 0.12)),
    "max_retest_deviation_atr_pct_mult": float(os.getenv("MAX_RETEST_DEVIATION_ATR_PCT_MULT", 0.22)),
    "trigger_pullback_band_atr": float(os.getenv("TRIGGER_PULLBACK_BAND_ATR", 0.34)),
    "trigger_deeper_retest_entry_atr": float(os.getenv("TRIGGER_DEEPER_RETEST_ENTRY_ATR", 0.18)),
    "trigger_retest_upper_band_atr": float(os.getenv("TRIGGER_RETEST_UPPER_BAND_ATR", 0.08)),
    "trigger_pullback_lookback_candles": 2,
    "trigger_ema_buffer_atr": 0.05,
    "trigger_confirm_body_ratio": 0.15,
    "trigger_min_body_ratio": float(os.getenv("TRIGGER_MIN_BODY_RATIO", 0.35)),
    "trigger_require_reclaim": os.getenv("TRIGGER_REQUIRE_RECLAIM", "true").lower() == "true",
    "trigger_require_rejection": os.getenv("TRIGGER_REQUIRE_REJECTION", "true").lower() == "true",
    "trigger_require_near_retest": os.getenv("TRIGGER_REQUIRE_NEAR_RETEST", "true").lower() == "true",
    "trigger_require_ema_alignment": os.getenv("TRIGGER_REQUIRE_EMA_ALIGNMENT", "true").lower() == "true",
    "trigger_require_ema_slope": os.getenv("TRIGGER_REQUIRE_EMA_SLOPE", "false").lower() == "true",
    "trigger_min_close_location": float(os.getenv("TRIGGER_MIN_CLOSE_LOCATION", 0.45)),
    "trigger_breakout_hold_atr": float(os.getenv("TRIGGER_BREAKOUT_HOLD_ATR", 0.05)),
    "allow_continuation_entry": os.getenv("ALLOW_CONTINUATION_ENTRY", "true").lower() == "true",
    "continuation_impulse_min_atr": float(os.getenv("CONTINUATION_IMPULSE_MIN_ATR", 1.0)),
    "continuation_impulse_max_atr": float(os.getenv("CONTINUATION_IMPULSE_MAX_ATR", 2.1)),
    "continuation_impulse_lookback_candles": int(os.getenv("CONTINUATION_IMPULSE_LOOKBACK_CANDLES", 16)),
    "continuation_min_pullback_fib": float(os.getenv("CONTINUATION_MIN_PULLBACK_FIB", 0.382)),
    "continuation_min_pullback_candles": int(os.getenv("CONTINUATION_MIN_PULLBACK_CANDLES", 2)),
    "continuation_max_distance_atr": float(os.getenv("CONTINUATION_MAX_DISTANCE_ATR", 0.60)),
    "continuation_max_against_wick_ratio": float(os.getenv("CONTINUATION_MAX_AGAINST_WICK_RATIO", 0.50)),
    "continuation_max_chase_atr": float(os.getenv("CONTINUATION_MAX_CHASE_ATR", 0.25)),
    "continuation_pullback_entry_atr": float(os.getenv("CONTINUATION_PULLBACK_ENTRY_ATR", 0.08)),
    "continuation_pullback_tolerance_bps": float(os.getenv("CONTINUATION_PULLBACK_TOLERANCE_BPS", 10)),
    "max_queue_impulse_atr": 3.20,
    "continuation_min_body_ratio": float(os.getenv("CONTINUATION_MIN_BODY_RATIO", 0.58)),
    "continuation_rsi_long_max": float(os.getenv("CONTINUATION_RSI_LONG_MAX", 56)),
    "continuation_rsi_short_min": float(os.getenv("CONTINUATION_RSI_SHORT_MIN", 44)),
    "continuation_rsi_long_min": 50,
    "continuation_rsi_short_max": 50,
    "continuation_min_close_location": float(os.getenv("CONTINUATION_MIN_CLOSE_LOCATION", 0.60)),
    "continuation_breakout_hold_atr": float(os.getenv("CONTINUATION_BREAKOUT_HOLD_ATR", 0.10)),
    "continuation_require_ema_alignment": os.getenv("CONTINUATION_REQUIRE_EMA_ALIGNMENT", "true").lower() == "true",
    "continuation_require_ema_slope": os.getenv("CONTINUATION_REQUIRE_EMA_SLOPE", "true").lower() == "true",
    "continuation_ema_slope_lookback": int(os.getenv("CONTINUATION_EMA_SLOPE_LOOKBACK", 3)),
    "retest_rsi_long_min": float(os.getenv("RETEST_RSI_LONG_MIN", 50)),
    "retest_rsi_short_max": float(os.getenv("RETEST_RSI_SHORT_MAX", 50)),
    "trigger_require_close": os.getenv("TRIGGER_REQUIRE_CLOSE", "true").lower() == "true",
    "trigger_require_rsi": os.getenv("TRIGGER_REQUIRE_RSI", "true").lower() == "true",
    "trigger_max_distance_atr": float(os.getenv("TRIGGER_MAX_DISTANCE_ATR", 0.10)),
    "min_stop_atr": float(os.getenv("MIN_STOP_ATR", 0.50)),
    "min_stop_ticks": int(os.getenv("MIN_STOP_TICKS", 4)),
    "dynamic_cancel_candles": True,
    "high_vol_atr_percent": 1.2,
    "low_vol_atr_percent": 0.6,
    "high_vol_cancel_candles": 2,
    "low_vol_cancel_candles": 4,
    "strong_score_threshold": 68,
    "elite_score_threshold": 75,
    "tp2_rr_strong": 2.3,
    "tp2_rr_elite": 2.5,
    "dynamic_tp2_by_score": False,
    "adaptive_tp_enabled": os.getenv("ADAPTIVE_TP_ENABLED", "false").lower() == "true",
    "adaptive_tp_low_vol_atr_pct": float(os.getenv("ADAPTIVE_TP_LOW_VOL_ATR_PCT", 0.60)),
    "adaptive_tp_high_vol_atr_pct": float(os.getenv("ADAPTIVE_TP_HIGH_VOL_ATR_PCT", 1.80)),
    "adaptive_tp_low_vol_expand": float(os.getenv("ADAPTIVE_TP_LOW_VOL_EXPAND", 0.08)),
    "adaptive_tp_high_vol_compress": float(os.getenv("ADAPTIVE_TP_HIGH_VOL_COMPRESS", 0.20)),
    "adaptive_tp_strong_trend_expand": float(os.getenv("ADAPTIVE_TP_STRONG_TREND_EXPAND", 0.10)),
    "adaptive_tp_weak_trend_compress": float(os.getenv("ADAPTIVE_TP_WEAK_TREND_COMPRESS", 0.12)),
    "adaptive_tp_spread_ref_bps": float(os.getenv("ADAPTIVE_TP_SPREAD_REF_BPS", 6.0)),
    "adaptive_tp_spread_penalty_max": float(os.getenv("ADAPTIVE_TP_SPREAD_PENALTY_MAX", 0.18)),
    "adaptive_tp_min_rr_mult": float(os.getenv("ADAPTIVE_TP_MIN_RR_MULT", 0.75)),
    "adaptive_tp_max_rr_mult": float(os.getenv("ADAPTIVE_TP_MAX_RR_MULT", 1.35)),
    "adaptive_tp2_rr_max": float(os.getenv("ADAPTIVE_TP2_RR_MAX", 2.4)),
    "adaptive_tp3_rr_max": float(os.getenv("ADAPTIVE_TP3_RR_MAX", 3.0)),
    "adaptive_tp2_bonus_max": float(os.getenv("ADAPTIVE_TP2_BONUS_MAX", 0.25)),
    "adaptive_tp3_bonus_max": float(os.getenv("ADAPTIVE_TP3_BONUS_MAX", 0.65)),
    "adaptive_tp_score_floor": float(os.getenv("ADAPTIVE_TP_SCORE_FLOOR", 4.0)),
    "adaptive_tp_score_ceiling": float(os.getenv("ADAPTIVE_TP_SCORE_CEILING", 8.5)),
    "volume_confirmation_enabled": os.getenv("VOLUME_CONFIRMATION_ENABLED", "true").lower() == "true",
    "volume_hard_block": os.getenv("VOLUME_HARD_BLOCK", "true").lower() == "true",
    "volume_min_ratio": float(os.getenv("VOLUME_MIN_RATIO", 0.72)),
    "volume_soft_floor_ratio": float(os.getenv("VOLUME_SOFT_FLOOR_RATIO", 0.58)),
    "adx_filter_enabled": os.getenv("ADX_FILTER_ENABLED", "true").lower() == "true",
    "adx_hard_block": os.getenv("ADX_HARD_BLOCK", "true").lower() == "true",
    "adx_min_value": float(os.getenv("ADX_MIN_VALUE", 18)),
    "adx_soft_floor": float(os.getenv("ADX_SOFT_FLOOR", 14)),
    "market_structure_enabled": os.getenv("MARKET_STRUCTURE_ENABLED", "true").lower() == "true",
    "market_structure_lookback": int(os.getenv("MARKET_STRUCTURE_LOOKBACK", 5)),
    "range_midpoint_filter_enabled": os.getenv("RANGE_MIDPOINT_FILTER_ENABLED", "true").lower() == "true",
    "range_midpoint_lookback_5m": int(os.getenv("RANGE_MIDPOINT_LOOKBACK_5M", 24)),
    "range_midpoint_buffer_atr": float(os.getenv("RANGE_MIDPOINT_BUFFER_ATR", 0.12)),
    "range_midpoint_buffer_span_ratio": float(os.getenv("RANGE_MIDPOINT_BUFFER_SPAN_RATIO", 0.06)),
    "ema_compression_filter_enabled": os.getenv("EMA_COMPRESSION_FILTER_ENABLED", "true").lower() == "true",
    "ema8_21_min_sep_atr": float(os.getenv("EMA8_21_MIN_SEP_ATR", 0.10)),
    "ema21_55_min_sep_atr": float(os.getenv("EMA21_55_MIN_SEP_ATR", 0.18)),
    "price_to_ema21_too_close_atr": float(os.getenv("PRICE_TO_EMA21_TOO_CLOSE_ATR", 0.10)),
    "vwap_soft_tolerance_pct": float(os.getenv("VWAP_SOFT_TOLERANCE_PCT", 0.18)),
    "directional_rsi5m_long_max": float(os.getenv("DIRECTIONAL_RSI5M_LONG_MAX", 66)),
    "directional_rsi1m_long_max": float(os.getenv("DIRECTIONAL_RSI1M_LONG_MAX", 68)),
    "directional_rsi5m_short_min": float(os.getenv("DIRECTIONAL_RSI5M_SHORT_MIN", 34)),
    "directional_rsi1m_short_min": float(os.getenv("DIRECTIONAL_RSI1M_SHORT_MIN", 32)),
    "entry_volume_spike_ratio": float(os.getenv("ENTRY_VOLUME_SPIKE_RATIO", 1.15)),
    "entry_rsi_long_min": float(os.getenv("ENTRY_RSI_LONG_MIN", 45)),
    "entry_rsi_long_max": float(os.getenv("ENTRY_RSI_LONG_MAX", 72)),
    "entry_rsi_short_min": float(os.getenv("ENTRY_RSI_SHORT_MIN", 36)),
    "entry_rsi_short_max": float(os.getenv("ENTRY_RSI_SHORT_MAX", 55)),
    "min_entry_score": float(os.getenv("MIN_ENTRY_SCORE", 3.6)),
    "continuation_min_entry_score": float(os.getenv("CONTINUATION_MIN_ENTRY_SCORE", 3.8)),
    "continuation_require_volume_spike": os.getenv("CONTINUATION_REQUIRE_VOLUME_SPIKE", "false").lower() == "true",
    "long_only_mode": os.getenv("LONG_ONLY_MODE", "true").lower() == "true",
    "long_1h_ema_separation_min": float(os.getenv("LONG_1H_EMA_SEPARATION_MIN", 0.003)),
    "pump_lookback_12_threshold": float(os.getenv("PUMP_LOOKBACK_12_THRESHOLD", 0.12)),
    "pump_lookback_24_threshold": float(os.getenv("PUMP_LOOKBACK_24_THRESHOLD", 0.18)),
    "pump_pullback_required": os.getenv("PUMP_PULLBACK_REQUIRED", "false").lower() == "true",
    "pump_pullback_percent": float(os.getenv("PUMP_PULLBACK_PERCENT", 0.04)),
    "setup_hl_lookback": int(os.getenv("SETUP_HL_LOOKBACK", 10)),
    "setup_rsi15_min": float(os.getenv("SETUP_RSI15_MIN", 52.0)),
    "range_15m_lookback": int(os.getenv("RANGE_15M_LOOKBACK", 12)),
    "range_15m_min_pct": float(os.getenv("RANGE_15M_MIN_PCT", 0.018)),
    "atr_15m_min_pct": float(os.getenv("ATR_15M_MIN_PCT", 0.006)),
    "range_5m_lookback": int(os.getenv("RANGE_5M_LOOKBACK", 20)),
    "range_5m_min_pct": float(os.getenv("RANGE_5M_MIN_PCT", 0.012)),
    "bb_width_min": float(os.getenv("BB_WIDTH_MIN", 0.015)),
    "resistance_lookback": int(os.getenv("RESISTANCE_LOOKBACK", 20)),
    "resistance_min_distance_pct": float(os.getenv("RESISTANCE_MIN_DISTANCE_PCT", 0.008)),
    "entry_rsi5m_min": float(os.getenv("ENTRY_RSI5M_MIN", 54.0)),
    "entry_volume_breakout_ratio": float(os.getenv("ENTRY_VOLUME_BREAKOUT_RATIO", 1.2)),
    "entry_volume_retest_ratio": float(os.getenv("ENTRY_VOLUME_RETEST_RATIO", 1.0)),
    "entry_min_ema7_closes": int(os.getenv("ENTRY_MIN_EMA7_CLOSES", 2)),
    "breakout_followthrough_candles": int(os.getenv("BREAKOUT_FOLLOWTHROUGH_CANDLES", 2)),
}

RISK_CONFIG = {
    "leverage": int(os.getenv("LEVERAGE", 3)),
    "position_size_mode": os.getenv("POSITION_SIZE_MODE", "risk_based").strip().lower(),
    "risk_mode": os.getenv("RISK_MODE", "hybrid"),
    "use_fixed_sl_usdt": os.getenv("USE_FIXED_SL_USDT", "true").lower() == "true",
    "adaptive_sl_enabled": os.getenv("ADAPTIVE_SL_ENABLED", "false").lower() == "true",
    "adaptive_sl_min_usdt": float(os.getenv("ADAPTIVE_SL_MIN_USDT", 10.0)),
    "adaptive_sl_base_usdt": float(os.getenv("ADAPTIVE_SL_BASE_USDT", 20.0)),
    "adaptive_sl_max_usdt": float(os.getenv("ADAPTIVE_SL_MAX_USDT", 40.0)),
    "adaptive_sl_score_floor": float(os.getenv("ADAPTIVE_SL_SCORE_FLOOR", 58.0)),
    "adaptive_sl_score_ceiling": float(os.getenv("ADAPTIVE_SL_SCORE_CEILING", 78.0)),
    "adaptive_sl_low_vol_atr_pct": float(os.getenv("ADAPTIVE_SL_LOW_VOL_ATR_PCT", 0.6)),
    "adaptive_sl_high_vol_atr_pct": float(os.getenv("ADAPTIVE_SL_HIGH_VOL_ATR_PCT", 1.8)),
    "adaptive_sl_vol_penalty_max": float(os.getenv("ADAPTIVE_SL_VOL_PENALTY_MAX", 0.22)),
    "fixed_sl_usdt": float(os.getenv("FIXED_SL_USDT", 20.0)),
    "min_risk_per_trade": float(os.getenv("MIN_RISK_PER_TRADE", 20.0)),
    "strict_fixed_sl_enforce": os.getenv("STRICT_FIXED_SL_ENFORCE", "true").lower() == "true",
    "fixed_sl_min_effective_ratio": float(os.getenv("FIXED_SL_MIN_EFFECTIVE_RATIO", 0.90)),
    "margin_capped_fixed_sl_min_effective_ratio": float(os.getenv("MARGIN_CAPPED_FIXED_SL_MIN_EFFECTIVE_RATIO", 0.55)),
    "margin_capped_min_effective_sl_floor_usdt": float(os.getenv("MARGIN_CAPPED_MIN_EFFECTIVE_SL_FLOOR_USDT", 10.0)),
    "max_risk_per_trade": float(os.getenv("MAX_RISK_PER_TRADE", 20.0)),
    "max_sl_usdt": float(os.getenv("MAX_SL_USDT", 20.0)),
    "risk_percent_per_trade": float(os.getenv("RISK_PERCENT_PER_TRADE", 0.8)),
    "daily_max_losses": int(os.getenv("DAILY_MAX_LOSSES", 8)),
    "max_daily_loss_r": float(os.getenv("MAX_DAILY_LOSS_R", 8.0)),
    "max_same_direction_losses": int(os.getenv("MAX_SAME_DIRECTION_LOSSES", 4)),
    "daily_profit_target_percent": float(os.getenv("DAILY_PROFIT_TARGET_PERCENT", 5.0)),
    "daily_loss_limit_percent": float(os.getenv("DAILY_LOSS_LIMIT_PERCENT", 5.0)),
    "max_daily_trades": int(os.getenv("MAX_DAILY_TRADES", 20)),
    "loss_cooldown_minutes": int(os.getenv("LOSS_COOLDOWN_MINUTES", 5)),
    "min_time_between_trades_minutes": int(os.getenv("MIN_TIME_BETWEEN_TRADES_MINUTES", 2)),
    "min_position_size_usdt": float(os.getenv("MIN_POSITION_SIZE_USDT", 1500.0)),
    "max_position_size_usdt": float(os.getenv("MAX_POSITION_SIZE_USDT", 3000.0)),
    "min_effective_sl_usdt": float(os.getenv("MIN_EFFECTIVE_SL_USDT", 20.0)),
    "min_effective_tp1_usdt": float(os.getenv("MIN_EFFECTIVE_TP1_USDT", 30.0)),
    "min_preferred_notional_usdt": float(os.getenv("MIN_PREFERRED_NOTIONAL_USDT", 1500.0)),
    "enforce_min_effective_targets": os.getenv("ENFORCE_MIN_EFFECTIVE_TARGETS", "true").lower() == "true",
    "margin_capped_min_risk_floor_usdt": float(os.getenv("MARGIN_CAPPED_MIN_RISK_FLOOR_USDT", 2.0)),
    "margin_capped_min_risk_ratio": float(os.getenv("MARGIN_CAPPED_MIN_RISK_RATIO", 0.10)),
    "trailing_stop_enabled": True,
    "trailing_stop_percent": 1.0,
    "trailing_stop_activation_percent": 1.0,
}

TIME_CONFIG = {
    "start_hour": 0,
    "end_hour": 24,
    "enable_news_filter": os.getenv("ENABLE_NEWS_FILTER", "false").lower() == "true",
    "news_buffer_minutes": 15,
}

SCAN_INTERVAL_DEFAULT = 30 if BYBIT_TESTNET else 60

SCAN_CONFIG = {
    "timeframe": os.getenv("SCAN_TIMEFRAME", "1"),
    "bias_timeframe": os.getenv("BIAS_TIMEFRAME", "240"),
    "higher_timeframes": ["5", "15", "60"],
    "scan_all_linear_perps": os.getenv("SCAN_ALL_LINEAR_PERPS", "true").lower() == "true",
    "min_mtf_confirmations": int(os.getenv("MIN_MTF_CONFIRMATIONS", 2)),
    "kline_limit": int(os.getenv("KLINE_LIMIT", 120)),
    "kline_cache_ttl_seconds": int(os.getenv("KLINE_CACHE_TTL_SECONDS", 12)),
    "kline_stale_ttl_seconds": int(os.getenv("KLINE_STALE_TTL_SECONDS", 180)),
    "kline_min_request_interval_seconds": float(os.getenv("KLINE_MIN_REQUEST_INTERVAL_SECONDS", 0.12)),
    "kline_max_retries": int(os.getenv("KLINE_MAX_RETRIES", 4)),
    "kline_retry_base_seconds": float(os.getenv("KLINE_RETRY_BASE_SECONDS", 0.6)),
    "kline_retry_max_seconds": float(os.getenv("KLINE_RETRY_MAX_SECONDS", 8.0)),
    "ticker_snapshot_ttl_seconds": float(os.getenv("TICKER_SNAPSHOT_TTL_SECONDS", 3.0)),
    "scan_interval_seconds": int(os.getenv("SCAN_INTERVAL_SECONDS", 15)),
    "scan_batch_size": int(os.getenv("SCAN_BATCH_SIZE", 24)),
    "scan_batch_size_rate_limited": int(os.getenv("SCAN_BATCH_SIZE_RATE_LIMITED", 10)),
    "mtf_confirmation": True,
    "max_symbols": int(os.getenv("MAX_SYMBOLS", 24)),
    "min_turnover_usdt": float(os.getenv("MIN_TURNOVER_USDT", 1500000)),
    "min_trade_turnover_usdt": float(os.getenv("MIN_TRADE_TURNOVER_USDT", 5000000)),
    "max_trade_spread_bps": float(os.getenv("MAX_TRADE_SPREAD_BPS", 12.0)),
    "min_trade_price_usdt": float(os.getenv("MIN_TRADE_PRICE_USDT", 0.02)),
}

ORDERBOOK_CONFIG = {
    "enabled": True,
    "mode": "soft_score",
    "orderbook_weight": 0.3,
    "min_trade_score": float(os.getenv("MIN_TRADE_SCORE", 58)),
}


SABAH_OVERRIDES = {
    "strategy": {
        "min_total_score": float(os.getenv("SABAH_MIN_TOTAL_SCORE", 3.9)),
        "min_rr": float(os.getenv("SABAH_MIN_RR", 1.75)),
    },
    "execution": {
        "volume_confirmation_enabled": True,
        "volume_min_ratio": float(os.getenv("SABAH_VOLUME_MIN_RATIO", 0.85)),
        "volume_soft_floor_ratio": float(os.getenv("SABAH_VOLUME_SOFT_FLOOR_RATIO", 0.66)),
        "adx_filter_enabled": True,
        "adx_min_value": float(os.getenv("SABAH_ADX_MIN_VALUE", 20)),
        "adx_soft_floor": float(os.getenv("SABAH_ADX_SOFT_FLOOR", 16)),
        "min_entry_score": float(os.getenv("SABAH_MIN_ENTRY_SCORE", 3.9)),
        "long_only_mode": True,
        "long_1h_ema_separation_min": 0.003,
        "pump_lookback_12_threshold": 0.12,
        "pump_lookback_24_threshold": 0.18,
        "setup_rsi15_min": 52.0,
        "range_15m_min_pct": 0.018,
        "atr_15m_min_pct": 0.006,
        "range_5m_min_pct": 0.012,
        "bb_width_min": 0.015,
        "resistance_min_distance_pct": 0.008,
        "entry_rsi5m_min": 54.0,
        "entry_volume_breakout_ratio": 1.2,
        "entry_volume_retest_ratio": 1.0,
    },
    "scan": {
        "min_trade_turnover_usdt": float(os.getenv("SABAH_MIN_TRADE_TURNOVER_USDT", 6500000)),
        "max_trade_spread_bps": float(os.getenv("SABAH_MAX_TRADE_SPREAD_BPS", 10.0)),
    },
}


GECE_OVERRIDES = {
    "strategy": {
        "min_total_score": float(os.getenv("MIN_TOTAL_SCORE", 3.3)),
        "strong_total_score": 7.0,
        "retest_entry_score": 3.8,
        "continuation_entry_score": 2.6,
        "retest_sl_buffer_atr": 0.18,
        "min_rr": 1.20,
        "adx_min_trend": 18,
        "block_against_full_htf_consensus": True,
    },
    "execution": {
        "max_pending_setups": 18,
        "setup_requeue_cooldown_minutes": int(os.getenv("SETUP_REQUEUE_COOLDOWN_MINUTES", 15)),
        "pullback_tolerance_bps": max(3, int(os.getenv("PULLBACK_TOLERANCE_BPS", 3))),
        "support_lookback_candles": 24,
        "support_touch_atr": 0.25,
        "short_support_guard_enabled": False,
        "short_support_guard_distance_atr": 0.70,
        "short_support_guard_drop_atr": 2.0,
        "short_pullback_retest_required": False,
        "short_pullback_retest_band_atr": 0.45,
        "short_rejection_wick_body_ratio": 0.90,
        "long_support_bounce_enabled": False,
        "long_support_bounce_rsi_max": 35,
        "long_support_bounce_min_wick_body_ratio": 1.10,
        "long_support_bounce_min_drop_atr": 1.00,
        "continuation_min_pullback_fib": 0.18,
        "continuation_min_pullback_candles": 1,
        "continuation_impulse_min_atr": 0.55,
        "continuation_impulse_max_atr": 2.8,
        "continuation_max_distance_atr": 1.35,
        "continuation_max_against_wick_ratio": 0.60,
        "continuation_min_body_ratio": 0.38,
        "continuation_max_chase_atr": 0.35,
        "continuation_rsi_long_max": 64,
        "continuation_rsi_short_min": 36,
        "continuation_rsi_long_min": 46,
        "continuation_rsi_short_max": 52,
        "retest_rsi_long_min": 48,
        "retest_rsi_short_max": 52,
        "trigger_require_reclaim": False,
        "trigger_require_near_retest": False,
        "trigger_require_rejection": True,
        "trigger_require_close": True,
        "trigger_require_ema_alignment": True,
        "trigger_require_ema_slope": False,
        "trigger_min_body_ratio": 0.35,
        "trigger_min_close_location": 0.45,
        "trigger_breakout_hold_atr": 0.01,
        "continuation_min_close_location": 0.52,
        "continuation_breakout_hold_atr": 0.03,
        "continuation_require_ema_alignment": True,
        "continuation_require_ema_slope": False,
        "continuation_require_volume_spike": False,
        "allow_continuation_entry": True,
        "continuation_min_entry_score": 3.8,
        "min_stop_atr": float(os.getenv("MIN_STOP_ATR", 0.50)),
        "max_chase_atr": float(os.getenv("MAX_CHASE_ATR", 0.45)),
        "hard_no_chase_atr": float(os.getenv("HARD_NO_CHASE_ATR", 0.80)),
        "hard_chase_reanchor_enabled": True,
        "hard_chase_reanchor_max_atr": 1.10,
        "hard_chase_reanchor_min_score": 8.8,
        "trigger_max_distance_atr": 0.18,
        "max_retest_deviation_pct": 0.18,
        "adaptive_tp_enabled": False,
        "adaptive_tp_low_vol_atr_pct": 0.55,
        "adaptive_tp_high_vol_atr_pct": 1.60,
        "adaptive_tp_high_vol_compress": 0.24,
        "adaptive_tp_spread_ref_bps": 5.0,
        "adaptive_tp_spread_penalty_max": 0.22,
        "volume_confirmation_enabled": True,
        "volume_hard_block": False,
        "volume_min_ratio": float(os.getenv("VOLUME_MIN_RATIO", 0.62)),
        "volume_soft_floor_ratio": float(os.getenv("VOLUME_SOFT_FLOOR_RATIO", 0.48)),
        "adx_filter_enabled": True,
        "adx_hard_block": False,
        "adx_min_value": 12,
        "adx_soft_floor": 9,
        "market_structure_enabled": True,
        "vwap_soft_tolerance_pct": 0.22,
        "entry_rsi_long_max": 76,
        "entry_rsi_short_min": 33,
        "min_entry_score": min(4.2, max(3.0, float(os.getenv("MIN_ENTRY_SCORE", 3.6)))),
        "long_only_mode": True,
        "long_1h_ema_separation_min": 0.003,
        "pump_lookback_12_threshold": 0.12,
        "pump_lookback_24_threshold": 0.18,
        "setup_rsi15_min": 52.0,
        "range_15m_min_pct": 0.018,
        "atr_15m_min_pct": 0.006,
        "range_5m_min_pct": 0.012,
        "bb_width_min": 0.015,
        "resistance_min_distance_pct": 0.008,
        "entry_rsi5m_min": 54.0,
        "entry_volume_breakout_ratio": 1.2,
        "entry_volume_retest_ratio": 1.0,
    },
    "scan": {
        "max_symbols": int(os.getenv("MAX_SYMBOLS", 24)),
        "min_turnover_usdt": 1000000,
        "min_trade_turnover_usdt": 2000000,
        "max_trade_spread_bps": 15.0,
        "min_trade_price_usdt": 0.01,
    },
    "orderbook": {
        "min_trade_score": float(os.getenv("MIN_TRADE_SCORE", 48)),
    },
}


TRADING_MODE_ALIASES = {
    "sabah": "sabah",
    "morning": "sabah",
    "gece": "gece",
    "night": "gece",
    "night_current": "gece",
}

_effective_mode = TRADING_MODE_ALIASES.get(TRADING_MODE, "sabah")

if _effective_mode == "gece":
    STRATEGY_CONFIG.update(GECE_OVERRIDES["strategy"])
    EXECUTION_CONFIG.update(GECE_OVERRIDES["execution"])
    SCAN_CONFIG.update(GECE_OVERRIDES["scan"])
    ORDERBOOK_CONFIG.update(GECE_OVERRIDES["orderbook"])
elif _effective_mode == "sabah":
    STRATEGY_CONFIG.update(SABAH_OVERRIDES["strategy"])
    EXECUTION_CONFIG.update(SABAH_OVERRIDES["execution"])
    SCAN_CONFIG.update(SABAH_OVERRIDES["scan"])

ACTIVE_TRADING_MODE = _effective_mode

if FAST_TEST_MODE:
    STRATEGY_CONFIG.update(
        {
            "min_rr": 1.5,
            "volume_multiplier": 0.8,
            "min_body_ratio": 0.0,
            "min_sl_percent": 0.05,
            "max_sl_percent": 5.0,
        }
    )
    SCAN_CONFIG.update({"mtf_confirmation": False, "min_mtf_confirmations": 0})
    ORDERBOOK_CONFIG.update({"enabled": False, "min_trade_score": 0})
    EXECUTION_CONFIG.update(
        {
            "use_post_only": True,
            "limit_offset_bps": 1,
            "reprice_offset_bps": 0,
            "cancel_after_candles": 2,
        }
    )

NEWS_EVENTS = {
    "CPI": {"days": [10, 11, 12, 13], "hour": 13, "minute_range": (15, 45)},
    "FOMC": {"days": None, "hour": 19, "minute_range": (0, 30)},
    "NFP": {"weekday": 4, "day_max": 7, "hour": 13, "minute_range": (15, 45)},
}
